GH-1216: [TDR New Work Detection] Extend System Tests for COVID processing (#395)
* Update vault to work around NoClassDefFoundError.
* Checkpoint failing with PSQLException: FATAL: database ... does not exist 
   database "wfltest147f1cbf976046e68e6beb5eef728674" does not exist
* Spec validation still losing sink and source keys.
* Update most dependencies.
* Restore batch or covid request.
* Checkpoint "working" spec.clj.
* Lift strip-internals out of endpoint API transaction.
* New system test passing again.
* Use Ed's strip-internals fix.
* clojure -M:format
* Respond to comments but now there is no :name in response.
* clojure -M:format
* Make ::name optional for now.